<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AddEmp.aspx.cs" Inherits="threeTierApp.AddEmp" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table>
            <tr>
                <td>
                    Emp Name :
                </td>
                <td>
                    <asp:TextBox ID="txtEmpNm" runat="server"></asp:TextBox>
                </td>
            </tr>
             <tr>
                <td>
                    Emp Age :
                </td>
                <td>
                    <asp:TextBox ID="txtAge" runat="server"></asp:TextBox>
                </td>
            </tr>
             <tr>
                <td>
                    Emp Salary :
                </td>
                <td>
                    <asp:TextBox ID="txtSalary" runat="server"></asp:TextBox>
                </td>
            </tr>
             <tr>
                <td>
                    Department Name :
                </td>
                <td>
                    <asp:DropDownList ID="ddlDept" runat="server"></asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnAdd" runat="server" Text="Add Employee" OnClick="btnAdd_Click" />
                </td>
            </tr>
        </table>
    </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:GridView ID="GridView1" runat="server" emptydatatext="No data available."   Width="779px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowDataBound="GridView1_RowDataBound" AllowPaging="True" OnPageIndexChanging="GridView1_PageIndexChanging" PageSize="3" AllowSorting="True" Height="246px" OnSorting="GridView1_Sorting">
                <Columns>
                    <asp:TemplateField SortExpression="empName" HeaderText="EmpName">
                        
                        <ItemTemplate>
                            <asp:Label ID="lblNm" runat="server" Text='<%#Eval("empName") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEmpName" runat="server" Text='<%#Eval("empName") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField SortExpression="empAge" HeaderText="Emp Age">
                      
                        <ItemTemplate>
                            <asp:Label ID="lblAge" runat="server" Text='<%#Eval("empAge") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEmpAge" runat="server" Text='<%#Eval("empAge") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField SortExpression="empSalary" HeaderText="Salary">
                       
                        <ItemTemplate>
                            <asp:Label ID="lblSal" runat="server" Text='<%#Eval("empSalary") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEmpSalary" runat="server" Text='<%#Eval("empSalary") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField SortExpression="deptName" HeaderText="Dept Name">
                       
                        <ItemTemplate>
                            <asp:Label ID="lblDeptNm" runat="server" Text='<%#Eval("deptName") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:HiddenField ID="hDeptnm" runat="server" Value='<%#Eval("deptId") %>'></asp:HiddenField>
                            <asp:DropDownList ID="ddlDept" runat="server"></asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
        </asp:GridView>
    </form>
</body>
</html>
