//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTbl
    {
        public int Id { get; set; }
        public string empName { get; set; }
        public int empAge { get; set; }
        public decimal empSalary { get; set; }
        public int deptId { get; set; }
    
        public virtual dept dept { get; set; }
    }
}
